databases:
  - name: my_portfolio_db
    plan: starter
    ipAllowList: []
      

services:
  - type: web
    name: my_portfolio
    env: ruby
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: my_portfolio_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
  - type: redis
    name: redis-my-portfolio
    ipAllowList: []
    plan: free
    maxmemoryPolicy: noeviction